### ISSUE TITLE
Site is unavailable for the http://opendap.knmi.nl/

### ISSUE THREAD

**Issue by Nirav11** [SantanderMetGroup/climate4R#50] opened 2023-01-04 14:18 UTC
The site is unavailable for running the examples used in climate4R

http://opendap.knmi.nl/knmi/thredds/dodsC/e-obs_0.25regular/tx_0.25deg_reg_v17.0.nc

**Comment by jesusff** [comment] 2024-04-23 06:56
Duplicate of https://github.com/SantanderMetGroup/loadeR/issues/93

**Closed by jesusff** 2024-04-23 06:56 UTC
